In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("spotify_millsongdata.csv")

In [ ]:
df.head(8)

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...
5,ABBA,Burning My Bridges,/a/abba/burning+my+bridges_20003011.html,"Well, you hoot and you holler and you make me ..."
6,ABBA,Cassandra,/a/abba/cassandra_20002811.html,Down in the street they're all singing and sho...
7,ABBA,Chiquitita,/a/abba/chiquitita_20002978.html,"Chiquitita, tell me what's wrong \r\nYou're e..."

In [ ]:
df.tail(8)

,artist,song,link,text
57642,Ziggy Marley,Friend,/z/ziggy+marley/friend_20673508.html,[Chorus] \r\nI wanna thank you for the things...
57643,Ziggy Marley,G7,/z/ziggy+marley/g7_20531173.html,Seven richest countries in the world \r\nThem...
57644,Ziggy Marley,Generation,/z/ziggy+marley/generation_20531171.html,Many generation have passed away \r\nFighting...
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [ ]:
df.shape

(57650, 4)

In [ ]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [ ]:
df =df.sample(5000).drop('link', axis=1).reset_index(drop=True)

In [ ]:
df.head(10)

,artist,song,text
0,Van Morrison,A New Kind Of Man,There's a voice cryin' out in the wilderness ...
1,Ella Fitzgerald,Get Thee Behind Me Satan,"Get thee behind me, Satan \r\nI want to resis..."
2,Michael Bolton,Une Femme Comme Toi,Une Femme Comme Toi \r\n \r\nLes mots s'envo...
3,Kirsty Maccoll,Here Comes That Man Again,Here comes that man again \r\nIt's always rou...
4,Alan Parsons Project,Limelight,I can see the glow of a distant sun \r\nI can...
5,Willie Nelson,Did I Ever Love You,Did I ever ever love you? \r\nDid I ever real...
6,Rascal Flatts,I Won't Let Go,It's like a storm \r\nThat cuts a path \r\nI...
7,Great Big Sea,Company Of Fools,Many a truest word \r\nHas been spoken by the...
8,Imperials,Sail On,Sail on \r\nWhen the water gets high \r\nSai...
9,Guns N' Roses,Anything Goes,I've been thinkin' 'bout \r\nThinkin' 'bout s...

In [ ]:
df['text'][0]

"There's a voice cryin' out in the wilderness  \r\nAll your trails have not been in vain  \r\nAnd you're doin' the best you know how to do  \r\nGaining strength in the things that remain  \r\n  \r\nYou're part of the plan  \r\nFor a new kind of man, to come through  \r\n  \r\nThere's an angel that's watching right over you  \r\nAll your trials have not been in vain  \r\nWon't you lift your head up to the starry night  \r\nFinding strength in the things that remain  \r\n  \r\nYou're part of the plan  \r\nFor a new kind of man, to come through  \r\n  \r\nWhen a man comes through  \r\nHe must do what he's supposed to do  \r\nWhen a man comes through.  \r\nHe can't do what everyone expects him  \r\n  \r\nWon't you lift your head up to the mountain top  \r\nAll your trials have not been in vain  \r\nThere's a light that keeps shining up ahead of you  \r\nEvery step of the way that you take  \r\n  \r\nIt's part of the plan  \r\nFor a new kind of man  \r\nIt's part of the plan  \r\nFor a new kind of man, to come through  \r\nIt's part of the plan  \r\nFor a new kind of man  \r\nNew kind of man  \r\nNew kind of man\r\n\r\n"

In [ ]:
df.shape

(5000, 3)

Procecing

In [ ]:
df['text'] = df['text'].str.lower().replace(r'^\w\s', ' ').replace(r'\n', ' ', regex = True)

In [ ]:
df.tail(5)

,artist,song,text
4995,Red Hot Chili Peppers,Especially In Michigan,life is my friend \r rake it up to take it in...
4996,Hanson,One More,i sit here by myself \r just staring into spa...
4997,Gary Valenciano,Ikaw Lamang,bakit tayo nagkaganito \r binitiwang pangako ...
4998,Dire Straits,Down To The Waterline,sweet surrender on the quayside \r you rememb...
4999,Doobie Brothers,Echoes Of Love,i hear your voice everywhere \r it's echoes o...

In [ ]:
import nltk
from nltk.stem.porter import PorterStemmer

In [ ]:
stemmer = PorterStemmer()

In [ ]:
def token(txt):
    token = nltk.word_tokenize(txt)
    a = [stemmer.stem(w) for w in token]
    return " ".join(a)

In [ ]:
import nltk

nltk.download('punkt_tab')
nltk.download('punkt')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
token("Chiquitita, tell me what's wrong")

"chiquitita , tell me what 's wrong"

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
df['text'] = df['text'].fillna('').apply(lambda x: token(x))

In [ ]:
tfidvector = TfidfVectorizer(analyzer='word',stop_words='english')

In [ ]:
matrix = tfidvector.fit_transform(df['text'])

In [ ]:
similarity = cosine_similarity(matrix)

In [ ]:
similarity[0]

array([1.        , 0.01600617, 0.00165709, ..., 0.01459467, 0.02105746,
       0.01530834])

In [ ]:
sample_song = df['song'].iloc[0]
sample_song

'A New Kind Of Man'

In [ ]:
def recommendation(song_name):
    idx = df[df['song'] == song_name].index[0]
    distance = sorted(list(enumerate(similarity[idx])), reverse=True, key=lambda x:x[1])
    song = []
    for s_id in distance[1:8]:
        song.append(df.iloc[s_id[0]].song)

    return song

In [ ]:
recommendation(sample_song)

['It Takes All Kinds Of People',
 'For You',
 'Man On The Silver Mountain',
 'ManUNkind',
 'Mystic Man',
 'Love Of Another Kind',
 'Yeah Man']

In [ ]:
import pickle

In [ ]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [ ]:
pickle.dump(df,open('df.pkl','wb'))